name: Check for build warnings
on: [pull_request_target]

jobs:
  status_checker_job:
    runs-on: ubuntu-latest
    name: Checks the OpenPublishing.Build status check for build warnings
    steps:
    - uses: dotnet/doc-tools/actions/status-checker@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
