name: Check for build warnings
on: [pull_request_target]

jobs:
  status_checker_job:
    runs-on: ubuntu-latest
    name: Checks the OpenPublishing.Build status check for build warnings
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
      with:
        egress-policy: audit
    - uses: dotnet/doc-tools/actions/status-checker@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
